let mouseghover1 = document.getElementByClass("box")
let mouseghover2 = document.getElementByClass(`box boxb`)
let homeBtn= document.getElementById("Home")
let galleryBtn= document.getElementById("Gallery")
let ContactBtn= document.getElementById("Contat")
